appName: "my_ecommerce_system"
addr: ":8080"
db:
  driverName: "mysql"
  dataSourceName: "root:root@/my_ecommerce_system"
  maxOpenConns: 2000
  maxIdleConns: 1000
redis:
  host: "localhost"
  port: 6379
  db: 7
  password: "1234567"
gateway:
  writeList:
    - "/hello"
    - "/user/signUp"
    - "/user/signIn"
    - "/user/login"
jwt:
    expire: 900 # 15min